# @see http://girder.readthedocs.io/en/latest/development.html#initializing-the-database-for-a-test

users:
  - login: 'admin'
    password: 'password'
    firstName: 'First'
    lastName: 'Last'
    email: 'admin@email.com'
    admin: true

collections:
  - name: 'master'
    public: true
    creator: 'admin'
    import: 'files/master'

  - name: 'devel'
    public: true
    creator: 'admin'
    import: 'files/devel'

  - name: 'private'
    public: false
    creator: 'admin'
    import: 'files/private'
